### ISSUE TITLE
Other downstream tasks

### ISSUE THREAD

**Issue by vadimkantorov** [ajabri/videowalk#16]
@ajabri Have you tried evaluating on other downstream tasks? E.g. how do learned representations perform on object detection or instance segmentation?

Thank you!

**Comment by ajabri** [comment]
Unfortunately, I have not yet had a chance to thoroughly investigate this, though others are beginning to report results using the CRW model for tasks like segmentation (e.g. https://arxiv.org/abs/2101.06553). This is definitely something I'd like to investigate further. I imagine there is still work to be done to close the gap with other self-sup methods that rely on more contrived learning signals like hand-tuned data aug (as done in most SOTA contrastive learning methods).

**Comment by vadimkantorov** [comment]
Got it. Thanks!
