### ISSUE TITLE
Potential typo when creating Kinetics400 dataset

### ISSUE THREAD

**Issue by vadimkantorov** [ajabri/videowalk#17]
Kinetics400 dataset docs specify that `extensions` argument is a tuple `extensions=('avi',)`, while in [`train.py`](https://github.com/ajabri/videowalk/blob/master/code/train.py#L95) it's a string `extensions=('mp4')`: https://github.com/ajabri/videowalk/blob/master/code/train.py#L95. Even if this works for some reason, it would be clearer to remove this ambiguity

UPD: I found why it works under the hood: python's `str.endswith` which is used for verifying extensions can accept either a tuple or a plain string, and PyTorch doesn't check the type of the passed object, that's why it's a lucky go

**Comment by ajabri** [comment]
Thanks for the heads up!
