### ISSUE TITLE
Question about details in the inference time 

### ISSUE THREAD

**Issue by HowieMa** [ajabri/videowalk#2]
Hi, thank you for sharing such an awesome project. I have some questions about the details in your paper, and I sincerely hope you can help me solve them. 

1) In your appendix, you said that the radius on feature map considered for source node is 12, what does it mean? It seems that there is no definition for the radius in your main paper. Is it similar to the restricted attention area in MAST and CorrFlow? If so, do you still use the same radius for long term correspondence, like the correspondence between the 1st frame and 100th frame? 
2) In your appendix, the number of neighbors is 10, while in your main paper you use K=5 for the k-nearest neighbors (3.1.1). Thus I would like to know whether they are the same things or not. 
3) Could you please tell us when you will release the code? 

I would really appreciate it if you could help me. Look forward to your reply, thanks!

**Comment by ajabri** [comment]
Hi Howie,

Check out `test.py` and `utils/test_utils.py` for related details. 
I've also fixed  typos and put more details in the supplementary of the camera-ready (https://proceedings.neurips.cc/paper/2020/hash/e2ef524fbf3d9fe611d5a8e90fefdc9c-Abstract.html).

In short:
1. Yes, it is restricted attention. For simplicity, we always use the same radius, except with the first frame.
2. Sorry, this is a typo. You can use 10.
3. Sorry for the delay
