### ISSUE TITLE
How many epochs for training?

### ISSUE THREAD

**Issue by zxzhaoeric** [ajabri/videowalk#20]
Hi Allen,

Thanks for your great job. I am wondering how many epochs needed for training ? 
Seems like it takes more than 10 hours for one epoch.
Btw, is it necessary to use Flip=True for training? I don't quite understand the use of --Flip.

Thanks so much.

**Comment by vadimkantorov** [comment]
@ajabri do I understand correctly that `--flip` switches on ["buggy"](https://github.com/ajabri/videowalk#fixed-a-bug) mode?

**Comment by ajabri** [comment]
Hi all,

No, `--flip` is not required, and indeed it will slightly shuffle the set of nodes (left multiply instead of right multiply); you can completely ignore it.  

You should be able to get to 95% of transfer performance after about 10 epochs of training.
