### ISSUE TITLE
Loading Kinetics400 takes 10h

### ISSUE THREAD

**Issue by Steve-Tod** [ajabri/videowalk#3]
Hi, thank you for sharing your code. I'm trying to train on Kinetics400 with your code. From the progress bar, it seems it needs 10h to load the whole dataset. Is that the same case in your experiments?

![image](https://user-images.githubusercontent.com/26958167/99152263-ac93e900-26db-11eb-98af-2e289d6d48ad.png)

**Comment by ajabri** [comment]
Hi @Steve-Tod, thanks for your message.

Yes, this is expected, but it only happens once. The Kinetics400 class uses the `VideoClips` class (see https://github.com/pytorch/vision/blob/master/torchvision/datasets/video_utils.py), which precomputes dataset related metadata once. Make sure to use `--cache-dataset` to save this precomputed info.

**Comment by pansanity666** [comment]
> Hi, thank you for sharing your code. I'm trying to train on Kinetics400 with your code. From the progress bar, it seems it needs 10h to load the whole dataset. Is that the same case in your experiments?
> 
> ![image](https://user-images.githubusercontent.com/26958167/99152263-ac93e900-26db-11eb-98af-2e289d6d48ad.png)

Hi， may I ask how much storage is needed for caching the dataset?
