### ISSUE TITLE
Can you share your hardware specifications?

### ISSUE THREAD

**Issue by cheonjsr** [ajabri/videowalk#4]
Hi, thanks for sharing the code.

I'm trying to implement your testing code, but whenever during computing affinity matrices my computer went dead.

Can you share your hardware specifications?

Thanks

**Comment by ajabri** [comment]
Hi, could you please share the error message?

**Comment by cheonjsr** [comment]
Thanks for your response.

Preparing source (keys) and target (query) frame features require about 40G RAM memory.

Solved it.
