### ISSUE TITLE
Name error during visualization.

### ISSUE THREAD

**Issue by ecr23xx** [ajabri/videowalk#7]
Hi! Thanks for your great work. When I'm playing with your code, it raises an exception in [utils/visualize.py#L213](https://github.com/ajabri/videowalk/blob/2961521f359dac8533cf4ac8c2121e38eabf54d0/code/utils/visualize.py#L213).

```
NameError: name 'f1' is not defined
```

Do you have any solution?

**Comment by ajabri** [comment]
Hi, thanks for your interest! 

Oops, I must have introduced that bug when refactoring. I've fixed it in 8d786f97c6513e3b4438ed7e64eed0f30a453d7a.
